travis:
  secure:
    BINSTAR_TOKEN: qHUb+38XXaOs4Dh/KUJ+BBLAZFnhoBmXhwyLOE/+2Ru7ojD0zWptnVujftuIu2+0tNXabxtihV5kLDSjQjX2qswQ+5B2fP2TVKUyXX1EhEcrxlUIJegH0B1pT3kLCtA9Xc6YWQUJ1i2/RTCi3QIVbmPQHVwvOhg4x/y2A75noYyCRwBYTBS/mWx0xpM5PrNlSObTdO5gZ1I0Y0IU8TYfDcXGgLMF288cPy7aGnft1OXll3INbvFfSsNQN2Jix4ZCKNIysX66YChjy1ilDl3tDcEutI8Xp3ra8iOo7E5HJLc0QApDE7uj+QCXFVSbn2tB57WkMD2CB6111M44o4n9vXo+aUGv6rPw1QJovugTonbfsJFjtFR9euoFTjx5eVHqlTXXj+2r9Ae8VkmlyoYe52+aYqvuvmIZBOOFuVMVv14b6x8KfnsDEOwfbbODL/dvwXCzlkSiS1L1olH58TQ69d2vAxyKAcNgef9bdwoLlxBCvsU00yfzCG5pX6yO/T6oKFg0diBLzd3YQ6pQ42xoXY64JSkFd0B2I33643cIpUFFoLgsg42e/rrsvDTYPnTiTlxPY4Fp8r/EYjIhg+3cNwJbwk3IVmQBxJ4fmWnBlv1/iGagiaMaCa1nS/P008bvcXMp0hq4ji38YbcBRC4ENEnqY7+bEtVsMfcrnnU9ef8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
