travis:
  secure:
    BINSTAR_TOKEN: EnhVeZa9rkZuoAjbvrU6FII3uCTWP9G9w5w+msc0XCpu/MrHgDDcDBiy+Hk9YT1WA1cB175Bv+PG63HL2Lyo2tT5E3mZlM06pLlAcXDmZjMy177IccF9BTSU9lpTfIClps1NtqeEUCZ5ud45Wt9tBznmZNUCdiOE8qtSnaXjWnJmyHhxiWR/SVYi3XeAocrbdPbynI0Hi4HSzB5Yj6lo8S+HmsPydqCo5Z5FUBCTy1s0yxHXDA6jrvkfVX1MOFfhBSoyIPl1f0gO4zgcqIHWkg5BligYjS9i/MfvcyK4UulmmLafTQk4Yb9+5TolweakNX6GYcMQimBvgM+66y/J1WlUaj2yNK9pVZ2NvUU1UJDpA2ZAhOH9cXhK56jJa2MQa00eHXL3QjWfaimC/Hg41WNt43nNCOwh1dEC92/FPWYppT/9J+7MP1hmizOWzLRk6yJUYXkpFfqA8xMLM9tNpuyJpIa3/GwR/dij/PIRop5KMKejEqMXr9yrojDbzzUD0xKpsqRvxuCbDsMnZXpR5rDioBtfOpTEMCahGIoxh5dr9Lkje9NdhUcNNd1OlTfeWCeUtTBkUcQauSflw/RURoUK2CYbqtdc1DB8zmBjeNnsxxKTGU4mPZsJDPJu6yud3VJajhRPk0oafjn3EcUNxMVfQIvZbH1JumYi9kIXxDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
